export const getMenuQuery = /* GraphQL */ `
  query getMegaMenu{
    categoryList{
      id
      uid 
      name 
        children{
        id
        uid 
        include_in_menu 
        name 
        position 
        url_path 
        children{
            id
            uid 
            include_in_menu 
            name 
            position 
            url_path 
                children{
                    id
                    uid 
                    include_in_menu 
                    name 
                    position 
                    url_path 
                }
            }
        }
    }
  }
`;
